---
- name: Add Traefik repo
  kubernetes.core.helm_repository:
    name: traefik
    repo_url: https://traefik.github.io/charts

- name: Show Python interpreter
  ansible.builtin.debug:
    var: ansible_python_interpreter

- name: Show playbook Python
  ansible.builtin.debug:
    var: ansible_playbook_python

- name: Show current user
  ansible.builtin.command: whoami
  register: traefik_current_user
  changed_when: false

- name: Debug current user
  ansible.builtin.debug:
    var: traefik_current_user.stdout

- name: Create Traefik namespace
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}"
    name: "{{ traefik_namespace }}"
    api_version: v1
    kind: Namespace
    state: present


- name: Install Traefik
  kubernetes.core.helm:
    kubeconfig: "{{ kubeconfig_path }}"
    name: "{{ traefik_release_name }}"
    chart_ref: traefik/traefik
    namespace: "{{ traefik_namespace }}"
    create_namespace: true
