---
- name: Base starter for every machines or instances
  hosts: all
  become: true
  gather_facts: false

  pre_tasks:
    - name: Wait for SSH on every host
      ansible.builtin.wait_for_connection:
        delay: 5
        timeout: 300

    - name: Wait for cloud-init completion
      ansible.builtin.command:
        cmd: cloud-init status --wait
      changed_when: false
      timeout: 600

    - name: Gather facts
      ansible.builtin.setup:
        
  roles:
    - common
    - oh-my-zsh
    - docker