---
- name: Check helm exists
  command: helm version
  register: helm_check
  failed_when: false
  changed_when: false


- name: Download Helm install script
  get_url:
    url: https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
    dest: /tmp/install-helm.sh
    mode: "0755"
  when: helm_check.rc != 0


- name: Install Helm
  command: /tmp/install-helm.sh
  when: helm_check.rc != 0


- name: Verify Helm installation
  command: helm version
  register: helm_version
  changed_when: false


- name: Show Helm version
  debug:
    var: helm_version.stdout