apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: earthdx-tls
  namespace: earthdx
spec:
  secretName: earthdx-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - react.first-frost.site