[k8s-master]
setops-kubernetes-master-0 ansible_host=35.220.191.80
[k8s-worker]
setops-kubernetes-worker-0 ansible_host=35.220.153.27
[all:vars]
ansible_user=MSI
ansible_ssh_private_key_file=~/.ssh/id_ed25519
ansible_ssh_common_args=-o StrictHostKeyChecking=accept-new