[k8s-master]
setops-kubernetes-master-0 ansible_host=34.150.61.218
[k8s-worker]
setops-kubernetes-worker-0 ansible_host=34.96.155.21
[all:vars]
ansible_user=MSI
ansible_ssh_private_key_file=~/.ssh/id_ed25519
ansible_ssh_common_args=-o StrictHostKeyChecking=accept-new