---
- ansible.builtin.import_playbook: playbooks/baseline.yml
- ansible.builtin.import_playbook: playbooks/ci-cd.yml
- ansible.builtin.import_playbook: playbooks/code-quality.yml
- ansible.builtin.import_playbook: playbooks/artifact-storage.yml
