all:
  hosts:
    setops-kubernetes-master-0:
      ansible_host: 35.220.191.80
      ip: 10.170.0.12
      access_ip: 10.170.0.12

    setops-kubernetes-worker-0:
      ansible_host: 35.220.153.27
      ip: 10.170.0.11
      access_ip: 10.170.0.11

  children:

    kube_control_plane:
      hosts:
        setops-kubernetes-master-0:

    etcd:
      hosts:
        setops-kubernetes-master-0:

    kube_node:
      hosts:
        setops-kubernetes-worker-0:

    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:

  vars:
    ansible_user: MSI
    ansible_become: true
    ansible_become_method: sudo
    ansible_ssh_private_key_file: /home/MSI/.ssh/id_ed25519
    ansible_ssh_common_args: "-o UserKnownHostsFile=./.ssh/known_hosts -o StrictHostKeyChecking=accept-new"